vich_uploader:
    db_driver: orm

    mappings:
        enterprise_images:
            uri_prefix: '%enterprise_images%'
            upload_destination: '%kernel.project_dir%/public%enterprise_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
